'use strict';

export const ACTIVE_INDEX = 'ACTIVE_INDEX';
export const REQUEST_COMPANY = 'REQUEST_COMPANY';
export const RECEIVE_COMPANY = 'RECEIVE_COMPANY';
<<<<<<< HEAD
export const INVALIDATE_COMPANY = 'INVALIDATE_COMPANY';
export const FAILURE_COMPANY = 'FAILURE_COMPANY';
=======
export const FAILURE_COMPANY = 'FAILURE_COMPANY';
>>>>>>> ec93e24da254d8d5fe0d0eebfa330995bc840a0b
