'use strict';

export const ACTIVE_INDEX = 'ACTIVE_INDEX';
export const REQUEST_COMPANY = 'REQUEST_COMPANY';
export const RECEIVE_COMPANY = 'RECEIVE_COMPANY';
export const INVALIDATE_COMPANY = 'INVALIDATE_COMPANY';
export const FAILURE_COMPANY = 'FAILURE_COMPANY';
export const SELECT_NEWS = 'SELECT_NEWS';
export const REQUEST_COMPNEWS = 'REQUEST_COMPNEWS';
export const RECEIVE_COMPNEWS = 'RECEIVE_COMPNEWS';
export const INVALIDATE_COMPNEWS = 'INVALIDATE_COMPNEWS';
export const FAILURE_COMPNEWS = 'FAILURE_COMPNEWS';
export const REGSTEP = 'REGSTEP';
export const USERTYPE = 'USERTYPE';
export const POST_CHECKVALID = 'POST_CHECKVALID';
export const RECEIVE_CHECKVALID = 'RECEIVE_CHECKVALID';
export const FAILURE_CHECKVALID = 'RECEIVE_CHECKVALID';
export const ISFOCUS = 'ISFOCUS';
export const ITEMTIPS = 'ITEMTIPS';
export const ITEM_INVALID = 'ITEM_INVALID';
export const AGREE = 'AGRREE';

